-- ============================================
-- InferenceBrake DATABASE SCHEMA (Supabase)
-- Run this in your Supabase SQL Editor
-- ============================================

-- Enable required extensions
-- CREATE EXTENSION IF NOT EXISTS "uuid-ossp" SCHEMA "extensions"; not needed, gen_random_uuid() is available
CREATE EXTENSION IF NOT EXISTS "vector";

-- ============================================
-- USERS TABLE
-- ============================================
CREATE TABLE users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT UNIQUE NOT NULL,
  api_key TEXT UNIQUE NOT NULL,
  plan TEXT NOT NULL DEFAULT 'hobby', -- hobby, pro, enterprise
  daily_limit INTEGER NOT NULL DEFAULT 1000,
  checks_today INTEGER NOT NULL DEFAULT 0,
  webhook_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create the increment function
CREATE OR REPLACE FUNCTION increment_usage(user_uuid UUID)
RETURNS void AS $$
BEGIN
  UPDATE users 
  SET checks_today = checks_today + 1 
  WHERE id = user_uuid;
END;
$$ LANGUAGE plpgsql;

-- Grant permission so the Edge Function (using service_role) can call it
GRANT EXECUTE ON FUNCTION increment_usage(UUID) TO service_role;

-- Reset daily counters at midnight (UTC)
CREATE OR REPLACE FUNCTION reset_daily_checks()
RETURNS void AS $$
BEGIN
  UPDATE users SET checks_today = 0;
END;
$$ LANGUAGE plpgsql;

-- TODO Schedule daily reset (requires pg_cron extension or external cron)
-- Alternative: handle in application layer

-- Index for fast API key lookup
CREATE INDEX idx_users_api_key ON users(api_key);

-- ============================================
-- REASONING HISTORY TABLE
-- ============================================
CREATE TABLE reasoning_history (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id TEXT NOT NULL,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  step_number INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  reasoning TEXT NOT NULL,
  action TEXT,  -- Extracted action for repetition detection
  embedding vector(384), -- gte-small 384 dims, openai ai-embeddings-v1 1536 dimensions
  similarity FLOAT,
  loop_detected BOOLEAN NOT NULL DEFAULT FALSE,
  metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX idx_reasoning_session ON reasoning_history(session_id, step_number);
CREATE INDEX idx_reasoning_user ON reasoning_history(user_id);
CREATE INDEX idx_reasoning_created ON reasoning_history(created_at);

-- Auto-delete old history (keep last 30 days)
CREATE OR REPLACE FUNCTION delete_old_history()
RETURNS void AS $$
BEGIN
  DELETE FROM reasoning_history 
  WHERE created_at < NOW() - INTERVAL '30 days';
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- METRICS TABLE (for analytics)
-- ============================================
CREATE TABLE metrics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  session_id TEXT NOT NULL,
  loop_detected BOOLEAN NOT NULL,
  similarity FLOAT,
  estimated_cost_saved FLOAT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_metrics_user ON metrics(user_id);
CREATE INDEX idx_metrics_created ON metrics(created_at);

-- ============================================
-- ALERTS TABLE
-- ============================================
CREATE TABLE alerts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  session_id TEXT NOT NULL,
  severity TEXT NOT NULL, -- warning, danger
  message TEXT NOT NULL,
  acknowledged BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_alerts_user ON alerts(user_id, acknowledged);

-- ============================================
-- ROW LEVEL SECURITY (RLS)
-- ============================================

-- Enable RLS on all tables
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE reasoning_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE alerts ENABLE ROW LEVEL SECURITY;

-- Users can only see their own data
CREATE POLICY "Users can view own data"
  ON users FOR SELECT
  USING (auth.uid() = id);

CREATE POLICY "Users can view own history"
  ON reasoning_history FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can view own metrics"
  ON metrics FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can view own alerts"
  ON alerts FOR SELECT
  USING (auth.uid() = user_id);

-- Service role can do everything (for API)
CREATE POLICY "Service role full access users"
  ON users FOR ALL
  USING (true);

CREATE POLICY "Service role full access history"
  ON reasoning_history FOR ALL
  USING (true);

CREATE POLICY "Service role full access metrics"
  ON metrics FOR ALL
  USING (true);

CREATE POLICY "Service role full access alerts"
  ON alerts FOR ALL
  USING (true);

-- ============================================
-- HELPER FUNCTIONS
-- ============================================

-- Generate API key
CREATE OR REPLACE FUNCTION generate_api_key()
RETURNS TEXT AS $$
BEGIN
  RETURN 'ib_' || encode(gen_random_bytes(32), 'hex');
END;
$$ LANGUAGE plpgsql;

-- Create new user with API key
CREATE OR REPLACE FUNCTION create_user(
  user_email TEXT,
  user_plan TEXT DEFAULT 'hobby'
)
RETURNS TABLE(id UUID, email TEXT, api_key TEXT) AS $$
DECLARE
  new_api_key TEXT;
  new_user_id UUID;
BEGIN
  new_api_key := generate_api_key();
  
  INSERT INTO users (email, api_key, plan, daily_limit)
  VALUES (
    user_email,
    new_api_key,
    user_plan,
    CASE
      WHEN user_plan = 'hobby' THEN 1000
      WHEN user_plan = 'pro' THEN 10000
      ELSE 999999
    END
  )
  RETURNING users.id INTO new_user_id;
  
  RETURN QUERY SELECT new_user_id, user_email, new_api_key;
END;
$$ LANGUAGE plpgsql;

-- Get user stats
CREATE OR REPLACE FUNCTION get_user_stats(user_uuid UUID)
RETURNS TABLE(
  total_checks BIGINT,
  loops_detected BIGINT,
  total_savings FLOAT,
  avg_similarity FLOAT
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    COUNT(*)::BIGINT as total_checks,
    COUNT(*) FILTER (WHERE loop_detected = true)::BIGINT as loops_detected,
    COALESCE(SUM(estimated_cost_saved), 0)::FLOAT as total_savings,
    COALESCE(AVG(similarity), 0)::FLOAT as avg_similarity
  FROM metrics
  WHERE user_id = user_uuid;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- ANALYTICS VIEWS
-- ============================================

CREATE OR REPLACE VIEW daily_stats AS
SELECT
  DATE(created_at) as date,
  user_id,
  COUNT(*) as total_checks,
  COUNT(*) FILTER (WHERE loop_detected = true) as loops_detected,
  ROUND(AVG(similarity)::numeric, 3) as avg_similarity,
  ROUND(SUM(estimated_cost_saved)::numeric, 2) as total_savings
FROM metrics
GROUP BY DATE(created_at), user_id
ORDER BY date DESC;

-- ============================================
-- USEFUL QUERIES
-- ============================================

-- Get all sessions with loops for a user
-- SELECT DISTINCT session_id
-- FROM reasoning_history
-- WHERE user_id = '<your-user-id>' AND loop_detected = true;

-- Get session timeline
-- SELECT step_number, reasoning, similarity, loop_detected
-- FROM reasoning_history
-- WHERE session_id = '<session-id>'
-- ORDER BY step_number;

-- Top users by cost savings
-- SELECT u.email, SUM(m.estimated_cost_saved) as total_saved
-- FROM metrics m
-- JOIN users u ON m.user_id = u.id
-- GROUP BY u.email
-- ORDER BY total_saved DESC;
